version: '3.8'
services:
   agent:
     image: jenkins/ssh-agent:jdk11
     privileged: true
     user: root
     container_name: agent
     expose:
       - 22
     environment:
       - JENKINS_AGENT_SSH_PUBKEY=*******
   tunnel:
     container_name: cloudflared-tunnel-agent
     image: cloudflare/cloudflared
     restart: unless-stopped
     command: tunnel run
     environment:
       - TUNNEL_TOKEN=*****
